// DOM cache for Poetry Share app
export const dom = {
  app: document.getElementById('app'),
  loading: document.getElementById('loading-indicator'),
  modalBg: document.getElementById('modal-bg'),
  modal: document.getElementById('modal'),
  modalMessage: document.getElementById('modal-message'),
  modalActions: document.getElementById('modal-actions'),
  navLogin: document.getElementById('nav-login'),
  navRegister: document.getElementById('nav-register'),
  navLogout: document.getElementById('nav-logout'),
  navDiscover: document.getElementById('nav-discover'),
  navMyPoems: document.getElementById('nav-my-poems'),
  navAddPoem: document.getElementById('nav-add-poem'),
  currentUserId: document.getElementById('current-user-id'),
  headerSearchForm: document.getElementById('header-search-form'),
  headerSearchInput: document.getElementById('header-search-input'),
  headerSearchIcon: document.getElementById('header-search-icon'),
  headerSearchFormMobile: document.getElementById('header-search-form-mobile'),
  headerSearchInputMobile: document.getElementById('header-search-input-mobile'),
};
